# Generated by Django 4.0.6 on 2022-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('retail_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'clothes',
            },
        ),
    ]
