# Generated by Django 4.0.6 on 2022-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloth",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("W", "Women"), ("O", "Others")],
                default="W",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloth",
            name="size",
            field=models.CharField(
                choices=[
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="M",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
