# Generated by Django 4.0.6 on 2022-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_alter_category_options_remove_cloth_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('Chiffon', 'Chiffon'), ('Cotton', 'Cotton'), ('Crepe', 'Crepe'), ('Denim', 'Denim'), ('Lace', 'Lace'), ('Leather', 'Leather'), ('Linen', 'Linen'), ('Satin', 'Satin')], default='Cotton', max_length=30),
            preserve_default=False,
        ),
    ]
