# Generated by Django 4.0.6 on 2022-08-15 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_cloth_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='retail_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='sell_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
