# Generated by Django 4.0.6 on 2022-08-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cloth',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
