name: Lint

on: 
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      with:
        args: ". --check --exclude migrations"